// ─── Language type ─────────────────────────────────────────

export type Language = 'auto' | 'zh-CN' | 'en-US';

export function detectBrowserLanguage(): 'zh-CN' | 'en-US' {
  const lang = navigator.language || '';
  if (lang.toLowerCase().startsWith('zh')) return 'zh-CN';
  return 'en-US';
}

export function resolveLanguage(lang: Language): 'zh-CN' | 'en-US' {
  if (lang === 'auto') return detectBrowserLanguage();
  return lang;
}

// ─── Translation type ───────────────────────────────────────

export type Translations = typeof en;

// ─── English ───────────────────────────────────────────────

export const en = {
  // App
  appTitle: 'AI API Doctor',
  appSubtitle: 'by Link-AI',
  version: 'v0.2',

  // Nav
  navHome: 'Home',
  navProviders: 'Providers',
  navKeys: 'Keys',
  navModels: 'Models',
  navExport: 'Export',
  navSettings: 'Settings',

  // Status card
  notConfigured: 'Not configured',
  provider: 'Provider',
  baseUrl: 'Base URL',
  apiKey: 'API Key',
  notSet: 'Not set',
  activeModel: 'Active Model',
  noModelSelected: 'No model selected',
  exampleTag: 'Example',

  // Home
  runDiagnosis: 'Run Diagnosis',
  runningDiagnosis: 'Running Diagnosis…',
  loading: 'Loading…',
  passed: 'passed',
  ready: 'Ready',
  needsAttention: 'Needs attention',
  failed: 'Failed',
  incomplete: 'Incomplete',
  notTested: 'Not tested',

  // Diagnosis steps
  baseUrlFormat: 'Base URL Format',
  apiKeyValid: 'API Key Valid',
  modelsEndpoint: 'Models Endpoint',
  modelSelected: 'Model Selected',
  chatCompletion: 'Chat Completion',
  usageReported: 'Usage Reported',
  usageNotReported: 'Usage not reported',
  usageAudit: 'Usage Audit',

  // Step messages
  skippedNoModel: 'Skipped — no model selected.',
  skippedNoUsage: 'Skipped — no usage data.',
  skippedChatFailed: 'Skipped — chat failed.',
  skippedIpRestricted: 'Skipped — IP restricted.',
  skippedConcurrencyLimited: 'Skipped — concurrency limited.',
  skippedModelNotFound: 'Skipped — model not found.',
  skippedChannelUnavailable: 'Skipped — channel unavailable.',
  skippedEndpointNotFound: 'Skipped — endpoint not found.',
  skippedRateLimited: 'Skipped — rate limited.',
  skippedServerError: 'Skipped — server error.',
  skippedBadRequest: 'Skipped — bad request.',
  skippedChatNotTested: 'Chat completion was not tested.',
  noUsageInResponse: 'This provider did not return usage data. Token consumption cannot be audited from the response.',
  usageAuditDisclaimer: 'This tool checks whether response usage data exists and whether reported token usage looks unusual. It does not accuse providers of overbilling.',

  // Usage audit
  usageSkipped: 'Skipped — choose a model and run diagnosis first.',
  usageAvailable: 'Available',
  usageNotReportedBadge: 'Not reported',
  usageAnomaly: 'Anomaly',
  usageSkippedBadge: 'Skipped',
  usagePromptTokens: 'prompt tokens',
  usageCompletionTokens: 'completion tokens',
  usageTotalTokens: 'total tokens',
  usageLatency: 'latency',
  usageTokensPerSec: 'tokens/s',
  collapse: 'Collapse',
  expand: 'Expand',

  // Actions
  copyReport: 'Copy Report',
  copied: 'Copied!',
  copyFailed: 'Copy failed',
  copyMarkdown: 'Copy Markdown',
  copyGhIssue: 'Copy GitHub Issue',
  shareResult: 'Share Result',
  models: 'Models',
  export: 'Export',
  providers: 'Providers',

  // Empty state
  emptyNoProvider: 'No provider yet',
  emptyNoProviderHint: 'Add your API Base URL and API Key to run a local diagnosis.',
  addProvider: 'Add Provider',
  viewGuide: 'View Guide',

  // Example provider prompt
  needRefEnv: 'Need a reference environment?',
  needRefEnvHint: 'You can add an example provider and run the diagnosis again. The same diagnostic logic applies to every provider.',
  addExampleProvider: 'Add example provider',
  exampleProviderBy: 'The example provider is provided by Link-AI.',

  // Shareable card
  cardStatus: 'Status',
  cardChecks: 'Checks',
  cardProvider: 'Provider',
  cardBaseUrl: 'Base URL',
  cardModel: 'Model',
  cardNotSelected: 'Not selected',
  cardMainIssue: 'Main Issue',
  cardNoIssue: 'No major issue found',
  cardHttpStatus: 'HTTP Status',
  cardProviderMsg: 'Provider Message',
  cardSuggestion: 'Suggestion',
  cardNA: 'N/A',
  cardUsage: 'Usage',
  cardUsageReported: 'usage: $total total ($prompt prompt, $completion completion)',
  cardUsageNotReported: 'Usage not reported',
  cardUsageSkipped: 'Usage not tested',
  cardFooter: 'Generated by AI API Doctor',
  cardUrl: 'aiapidoctor.com',

  // Markdown report
  mdTitle: 'AI API Doctor Report',
  mdStatus: 'Status',
  mdChecks: 'Checks',
  mdProvider: 'Provider',
  mdBaseUrl: 'Base URL',
  mdApiKey: 'API Key',
  mdModel: 'Model',
  mdMainIssue: 'Main Issue',
  mdHttpStatus: 'HTTP Status',
  mdProviderMsg: 'Provider Message',
  mdSuggestion: 'Suggestion',
  mdNA: 'Not available',
  mdUsage: 'Usage',
  mdNoUsage: 'No usage data returned.',
  mdSafetyNote: 'API Key is masked. No full key is included.',
  mdGeneratedBy: 'Generated by AI API Doctor',

  // GH Issue
  ghTitle: 'API Diagnosis Issue',
  ghSummary: 'AI API Doctor found a configuration or permission issue.',
  ghEnv: 'Environment',
  ghResult: 'Result',
  ghFailedStep: 'Failed Step',
  ghSuggestion: 'Suggestion',
  ghUsage: 'Usage',
  ghSafety: 'Safety',
  ghPromptTokens: 'prompt tokens',
  ghCompletionTokens: 'completion tokens',
  ghTotalTokens: 'total tokens',
  ghUsageStatus: 'usage status',

  // Models page
  searchModels: 'Search models…',
  modelsLoaded: 'models',
  enterManually: 'Enter Model Manually',
  manualModelHint: 'Some relay providers do not expose /v1/models. Enter a model ID manually and test it directly.',
  setActive: 'Set Active',
  test: 'Test',
  cancel: 'Cancel',
  refresh: 'Refresh',
  noModelsLoaded: 'No models loaded.',
  enterModelManuallyOrRetry: 'Enter a model ID manually or retry.',
  testing: 'Testing…',
  testConnectivity: 'Test Connectivity',
  retry: 'Retry',
  connectivityOk: 'Connectivity OK',
  copiedShort: 'Copied!',
  active: 'Active',

  // Export page
  configuration: 'Configuration',
  download: 'Download',
  exportNote: 'Your API key will be included in the export. Keep the file secure and do not share it publicly.',

  // Settings page
  settings: 'Settings',
  language: 'Language',
  langAuto: 'Auto',
  langZhCN: '简体中文',
  langEnUS: 'English',
  activeModelLabel: 'Active Model',
  commonModelIds: 'Common IDs:',
  save: 'Save',
  saved: 'Saved!',
  clearAllLocalData: 'Clear All Local Data',
  clearDataConfirm: 'Are you sure you want to clear all local data? This will delete all providers, API keys, and settings. This action cannot be undone.',
  clearDataSuccess: 'All data has been cleared. Please refresh the extension.',
  dangerZone: 'Danger Zone',
  clearDataWarning: 'Permanently delete all providers, API keys, and settings from chrome.storage.local.',
  privacy: 'Privacy',
  privacyNote: 'All data is stored locally in your browser via chrome.storage.local. API keys are never uploaded to any server.',
  storageQuota: 'Storage quota',
  storageQuotaNote: 'Approximately 10MB.',
  helpFaq: 'Help & FAQ',
  faq: 'FAQ',
  faqDesc: '常见问题',
  modelGroupError: '403 Model Group Error',
  modelGroupErrorDesc: '403 分组错误',
  tokenUsageAudit: 'Token Usage Audit',
  tokenUsageAuditDesc: 'Token 消耗核对',
  privacyPolicy: 'Privacy',
  privacyPolicyDesc: '隐私政策',

  // About section
  aboutTitle: 'About',
  aboutDescription: 'AI API Doctor is publicly built by @norike0718.',
  aboutDescription2: 'The author builds SaaS and AI tools, with a focus on content workflows, AI API configuration, automation pipelines and developer tool experience.',
  aboutDescription3: 'Link-AI is a sponsor and one of the example providers. AI API Doctor supports any OpenAI-compatible API, and the same diagnostic logic applies to every provider.',

  // Error messages
  providerOrKeyNotConfigured: 'Provider or API key not configured. Please set up your configuration first.',
  noApiKeyConfigured: 'No API key configured.',
  unknownError: 'Unknown error.',
  networkError: 'Network error — could not reach the API server. Check your connection or base URL.',
  corsError: 'CORS error — the server blocked the request. The provider may not allow browser requests.',
  modelAccessDenied: 'Permission denied when loading the model list.',
  modelsUnsupported: 'Model listing endpoint not found (404).',
};

// ─── Chinese (Simplified) ─────────────────────────────────

export const zh: Translations = {
  // App
  appTitle: 'AI API 诊断助手',
  appSubtitle: 'by Link-AI',
  version: 'v0.2',

  // Nav
  navHome: '首页',
  navProviders: '服务商',
  navKeys: '密钥',
  navModels: '模型',
  navExport: '导出',
  navSettings: '设置',

  // Status card
  notConfigured: '未配置',
  provider: '服务商',
  baseUrl: '接口地址',
  apiKey: 'API 密钥',
  notSet: '未设置',
  activeModel: '当前模型',
  noModelSelected: '未选择模型',
  exampleTag: '示例',

  // Home
  runDiagnosis: '开始诊断',
  runningDiagnosis: '诊断进行中…',
  loading: '加载中…',
  passed: '通过',
  ready: '就绪',
  needsAttention: '需要注意',
  failed: '失败',
  incomplete: '不完整',
  notTested: '未检测',

  // Diagnosis steps
  baseUrlFormat: '地址格式',
  apiKeyValid: '密钥验证',
  modelsEndpoint: '模型列表接口',
  modelSelected: '模型选择',
  chatCompletion: '对话接口测试',
  usageReported: '用量返回',
  usageNotReported: '用量未返回',
  usageAudit: '用量核对',

  // Step messages
  skippedNoModel: '已跳过 — 未选择模型。',
  skippedNoUsage: '已跳过 — 无用量数据。',
  skippedChatFailed: '已跳过 — 对话请求失败。',
  skippedIpRestricted: '已跳过 — IP 限制。',
  skippedConcurrencyLimited: '已跳过 — 并发受限。',
  skippedModelNotFound: '已跳过 — 模型未找到。',
  skippedChannelUnavailable: '已跳过 — 渠道不可用。',
  skippedEndpointNotFound: '已跳过 — 端点未找到。',
  skippedRateLimited: '已跳过 — 请求被限流。',
  skippedServerError: '已跳过 — 服务器错误。',
  skippedBadRequest: '已跳过 — 请求格式错误。',
  skippedChatNotTested: '对话接口未被测试。',
  noUsageInResponse: '该服务商本次响应没有返回 usage 字段，无法从响应中核对 Token 消耗。',
  usageAuditDisclaimer: '用量核对用于检查本次响应是否返回 usage 字段，并提示 Token 消耗是否存在异常。它不会判断服务商是否故意多扣费。',

  // Usage audit
  usageSkipped: '未测试 — 请先选择模型并运行诊断。',
  usageAvailable: '正常',
  usageNotReportedBadge: '未返回',
  usageAnomaly: '数据异常',
  usageSkippedBadge: '已跳过',
  usagePromptTokens: 'prompt tokens',
  usageCompletionTokens: 'completion tokens',
  usageTotalTokens: 'total tokens',
  usageLatency: '响应延迟',
  usageTokensPerSec: 'tokens/s',
  collapse: '收起',
  expand: '展开',

  // Actions
  copyReport: '复制报告',
  copied: '已复制！',
  copyFailed: '复制失败',
  copyMarkdown: '复制 Markdown',
  copyGhIssue: '复制 Issue',
  shareResult: '分享结果',
  models: '模型',
  export: '导出',
  providers: '服务商',

  // Empty state
  emptyNoProvider: '还没有服务商',
  emptyNoProviderHint: '添加你的 API Base URL 和 API Key，开始本地诊断。',
  addProvider: '添加服务商',
  viewGuide: '查看新手指南',

  // Example provider prompt
  needRefEnv: '需要一个对照环境？',
  needRefEnvHint: '你可以添加示例服务商，再运行一次诊断。所有诊断逻辑对服务商一致。',
  addExampleProvider: '添加示例服务商',
  exampleProviderBy: '示例服务商由 Link-AI 提供。',

  // Shareable card
  cardStatus: '状态',
  cardChecks: '已通过',
  cardProvider: '服务商',
  cardBaseUrl: '接口地址',
  cardModel: '模型',
  cardNotSelected: '未选择',
  cardMainIssue: '主要问题',
  cardNoIssue: '未发现主要问题',
  cardHttpStatus: 'HTTP 状态码',
  cardProviderMsg: '服务商返回',
  cardSuggestion: '建议',
  cardNA: '暂无',
  cardUsage: '用量',
  cardUsageReported: '用量：$total total（$prompt prompt，$completion completion）',
  cardUsageNotReported: '未返回用量',
  cardUsageSkipped: '未测试用量',
  cardFooter: 'Generated by AI API Doctor',
  cardUrl: 'aiapidoctor.com',

  // Markdown report
  mdTitle: 'AI API Doctor Report',
  mdStatus: 'Status',
  mdChecks: 'Checks',
  mdProvider: 'Provider',
  mdBaseUrl: 'Base URL',
  mdApiKey: 'API Key',
  mdModel: 'Model',
  mdMainIssue: 'Main Issue',
  mdHttpStatus: 'HTTP Status',
  mdProviderMsg: 'Provider Message',
  mdSuggestion: 'Suggestion',
  mdNA: '暂无',
  mdUsage: 'Usage',
  mdNoUsage: 'No usage data returned.',
  mdSafetyNote: 'API Key is masked. No full key is included.',
  mdGeneratedBy: 'Generated by AI API Doctor',

  // GH Issue
  ghTitle: 'API 诊断问题',
  ghSummary: 'AI API Doctor 发现了配置、权限或用量返回问题。',
  ghEnv: '环境',
  ghResult: '结果',
  ghFailedStep: '失败步骤',
  ghSuggestion: '建议',
  ghUsage: '用量',
  ghSafety: '安全说明',
  ghPromptTokens: 'prompt tokens',
  ghCompletionTokens: 'completion tokens',
  ghTotalTokens: 'total tokens',
  ghUsageStatus: '用量状态',

  // Models page
  searchModels: '搜索模型…',
  modelsLoaded: '个模型',
  enterManually: '手动输入模型',
  manualModelHint: '部分中转服务不支持 /v1/models 接口，可手动输入模型 ID 进行测试。',
  setActive: '设为当前',
  test: '测试',
  cancel: '取消',
  refresh: '刷新',
  noModelsLoaded: '未加载到模型。',
  enterModelManuallyOrRetry: '手动输入模型 ID 或重试。',
  testing: '测试中…',
  testConnectivity: '测试连通性',
  retry: '重试',
  connectivityOk: '连接正常',
  copiedShort: '已复制！',
  active: '当前',

  // Export page
  configuration: '配置预览',
  download: '下载',
  exportNote: '导出的内容包含你的 API 密钥，请妥善保管，不要公开发布。',

  // Settings page
  settings: '设置',
  language: '界面语言',
  langAuto: '跟随系统',
  langZhCN: '简体中文',
  langEnUS: 'English',
  activeModelLabel: '当前模型',
  commonModelIds: '常用模型 ID：',
  save: '保存',
  saved: '已保存！',
  clearAllLocalData: '清除所有本地数据',
  clearDataConfirm: '确定要清除所有本地数据吗？此操作将删除所有服务商、API 密钥和设置，且不可恢复。',
  clearDataSuccess: '所有数据已清除，请刷新插件。',
  dangerZone: '危险操作',
  clearDataWarning: '永久删除 chrome.storage.local 中的所有服务商、API 密钥和设置。',
  privacy: '隐私',
  privacyNote: '所有数据存储在浏览器本地的 chrome.storage.local 中，API 密钥不会上传至任何服务器。',
  storageQuota: '存储空间',
  storageQuotaNote: '约 10MB。',
  helpFaq: '帮助与文档',
  faq: '常见问题',
  faqDesc: 'FAQ',
  modelGroupError: '403 分组错误',
  modelGroupErrorDesc: '403 Model Group Error',
  tokenUsageAudit: 'Token 消耗核对',
  tokenUsageAuditDesc: 'Token Usage Audit',
  privacyPolicy: '隐私政策',
  privacyPolicyDesc: 'Privacy',

  // About section
  aboutTitle: '关于',
  aboutDescription: 'AI API Doctor 由 @norike0718 发起并公开构建。',
  aboutDescription2: '作者长期构建 SaaS 和 AI 工具，关注内容工作流、AI API 配置、自动化生产线和开发者工具体验。',
  aboutDescription3: 'Link-AI 是项目赞助方和示例服务商之一。AI API Doctor 支持任何 OpenAI-compatible API，诊断逻辑不会因服务商不同而改变。',

  // Error messages
  providerOrKeyNotConfigured: '服务商或 API 密钥未配置，请先完成设置。',
  noApiKeyConfigured: '未配置 API 密钥。',
  unknownError: '未知错误。',
  networkError: '网络错误 — 无法连接 API 服务器，请检查网络或接口地址。',
  corsError: 'CORS 错误 — 服务器拒绝了请求，该服务商可能不允许浏览器访问。',
  modelAccessDenied: '获取模型列表时被拒绝访问。',
  modelsUnsupported: '模型列表接口未找到（404）。',
};

// ─── Dictionary map ────────────────────────────────────────

const translations: Record<'zh-CN' | 'en-US', Translations> = {
  'zh-CN': zh,
  'en-US': en,
};

// ─── Translation function ────────────────────────────────

export function t(lang: 'zh-CN' | 'en-US', key: keyof Translations): string {
  return translations[lang]?.[key] ?? translations['en-US']?.[key] ?? String(key);
}
