// ─── Language type ─────────────────────────────────────────

export type Language = 'auto' | 'zh-CN' | 'en-US';

export function detectBrowserLanguage(): 'zh-CN' | 'en-US' {
  const lang = navigator.language || '';
  if (lang.toLowerCase().startsWith('zh')) return 'zh-CN';
  return 'en-US';
}

export function resolveLanguage(lang: Language): 'zh-CN' | 'en-US' {
  if (lang === 'auto') return detectBrowserLanguage();
  return lang;
}

export type Translations = typeof en;

// ─── English ───────────────────────────────────────────────

export const en = {
  // App
  appTitle: 'AI API Doctor',
  version: 'v0.2',

  // Permission
  permissionDenied: 'The browser has not granted access to this API host. Run diagnosis again and allow access to continue.',
  permissionDeniedHint: 'Please grant permission when prompted and run diagnosis again.',

  // Nav
  navHome: 'Home',
  navModels: 'Models',
  navExport: 'Export',
  navHelp: 'Help',

  // Home
  apiConfiguration: 'API Configuration',
  pasteConnection: 'Paste Connection',
  pasteConnectionPlaceholder: 'Paste New API connection JSON, Base URL, or API Key',
  pasteConnectionHint: 'Supports New API format, e.g.: {"_type":"newapi_channel_conn","key":"sk-...","url":"https://api.example.com"}',
  providerName: 'Provider Name',
  providerNameOptional: 'Optional',
  providerNamePlaceholder: 'My Provider',
  baseUrl: 'Base URL',
  baseUrlRequired: 'Required',
  baseUrlPlaceholder: 'https://api.example.com/v1',
  apiKey: 'API Key',
  apiKeyRequired: 'Required',
  apiKeyPlaceholder: 'sk-...',
  modelId: 'Model ID',
  modelIdOptional: 'Optional but recommended',
  modelIdPlaceholder: 'gpt-4o, deepseek-chat, claude-opus-4.7',
  modelIdRecommended: 'Recommended',
  saveLocally: 'Save Locally',
  runDiagnosis: 'Run Diagnosis',
  runningDiagnosis: 'Running Diagnosis…',
  loading: 'Loading…',

  // Parse feedback
  parsedOk: 'Parsed connection info locally.',
  parseFailed: 'Could not parse this input. Please fill fields manually.',
  urlHintMissingV1: 'This URL may be missing /v1. Suggested: {url}. You can edit it manually.',

  // Example provider
  needExample: 'Need an example?',
  needExampleDesc: 'Use an example provider as a reference. The same diagnostic logic applies to every provider.',
  useExample: 'Use Example',
  exampleProviderBy: 'The example provider is provided by Link-AI.',

  // Quick Guide
  quickGuide: 'Quick Guide',
  guideStep1: 'Paste a New API connection JSON, or enter Base URL and API Key manually.',
  guideStep2: 'Enter a model ID or select one from Models.',
  guideStep3: 'Run Diagnosis.',
  guideStep4: 'Copy the report to your provider or support team.',

  // Diagnosis result labels
  passed: 'passed',
  ready: 'Ready',
  needsAttention: 'Needs attention',
  failed: 'Failed',
  skipped: 'Skipped',

  // Diagnosis steps
  baseUrlFormat: 'Base URL Format',
  apiKeyValid: 'API Key',
  modelsEndpoint: 'Models Endpoint',
  modelSelected: 'Model Selected',
  chatCompletion: 'Chat Completion',
  usageReported: 'Usage Reported',
  usageAudit: 'Usage Audit',

  // Report card
  diagnosisResult: 'Diagnosis Result',
  status: 'Status',
  checks: 'Checks',
  checksPassed: '{passed} / {total} passed',
  provider: 'Provider',
  baseUrl_: 'Base URL',
  model: 'Model',
  modelNotSelected: 'Not selected',
  mainIssue: 'Main Issue',
  noMajorIssue: 'No major issue found',
  httpStatus: 'HTTP Status',
  providerMessage: 'Provider Message',
  suggestion: 'Suggestion',
  na: 'N/A',
  usage: 'Usage',
  usageReportFormat: 'usage: {total} total ({prompt} prompt, {completion} completion)',
  usageNotReported: 'Usage not reported',
  usageSkipped: 'Usage not tested',
  latency: 'latency',
  tokensPerSec: 'tokens/s',
  reportFooter: 'Generated by AI API Doctor',
  reportUrl: 'aiapidoctor.com',

  // Copy buttons
  copyMarkdown: 'Copy Markdown',
  copyIssue: 'Copy Issue',
  copyResultText: 'Copy Result Text',
  copied: 'Copied!',
  copyFailed: 'Copy failed',

  // Usage audit
  usageAvailable: 'Available',
  usageNotReportedBadge: 'Not reported',
  usageAnomaly: 'Anomaly',
  usageSkippedBadge: 'Skipped',
  usagePromptTokens: 'prompt tokens',
  usageCompletionTokens: 'completion tokens',
  usageTotalTokens: 'total tokens',
  collapse: 'Collapse',
  expand: 'Expand',

  // Models page
  models: 'Models',
  searchModels: 'Search models…',
  modelsLoaded: 'models',
  enterManually: 'Enter Manually',
  manualModelHint: 'Some relay providers do not expose /v1/models. Enter a model ID manually.',
  setActive: 'Set Active',
  test: 'Test',
  cancel: 'Cancel',
  refresh: 'Refresh',
  noModelsLoaded: 'No models loaded.',
  enterModelManuallyOrRetry: 'Enter a model ID manually or retry.',
  testing: 'Testing…',
  testConnectivity: 'Test Connectivity',
  connectivityOk: 'OK',
  active: 'Active',
  modelsNoConfigTitle: 'No Configuration',
  modelsNoConfigDesc: 'Please enter Base URL and API Key on Home first.',

  // Export page
  export: 'Export',
  configuration: 'Configuration',
  download: 'Download',
  exportNote: 'Your API key will be included in the export. Keep the file secure.',
  noConfigExport: 'Please configure your API on Home first.',
  exportCline: 'Cline',
  exportContinue: 'Continue',
  exportOpenAI: 'OpenAI SDK',
  exportCurl: 'cURL',
  exportEnv: '.env',

  // Help page
  help: 'Help',
  quickGuideTitle: 'Quick Guide',
  helpFaq: 'FAQ',
  helpFaqDesc: '常见问题',
  modelGroupError: '403 Model Group Error',
  modelGroupErrorDesc: '403 分组错误',
  tokenUsageAudit: 'Token Usage Audit',
  tokenUsageAuditDesc: 'Token 消耗核对',
  aboutTitle: 'About',
  aboutDescription: 'AI API Doctor is publicly built by @norike0718.',
  aboutDescription2: 'Link-AI is a sponsor and one of the example providers. AI API Doctor supports any OpenAI-compatible API, and the same diagnostic logic applies to every provider.',
};

// ─── Chinese (Simplified) ─────────────────────────────────

export const zh: Translations = {
  // App
  appTitle: 'AI API 诊断助手',
  version: 'v0.2',

  // Permission
  permissionDenied: '浏览器未授权访问该 API 域名，无法发起诊断请求。你可以重新运行诊断并允许访问该域名。',
  permissionDeniedHint: '请在弹出的权限请求中点击允许，然后重新运行诊断。',

  // Nav
  navHome: '首页',
  navModels: '模型',
  navExport: '导出',
  navHelp: '帮助',

  // Home
  apiConfiguration: 'API 配置',
  pasteConnection: '粘贴连接信息',
  pasteConnectionPlaceholder: '粘贴 New API 连接信息、Base URL 或 API Key',
  pasteConnectionHint: '支持 New API 格式，例如：{"_type":"newapi_channel_conn","key":"sk-...","url":"https://api.example.com"}',
  providerName: '服务商名称',
  providerNameOptional: '选填',
  providerNamePlaceholder: '服务商 1',
  baseUrl: 'Base URL',
  baseUrlRequired: '必填',
  baseUrlPlaceholder: 'https://api.example.com/v1',
  apiKey: 'API Key',
  apiKeyRequired: '必填',
  apiKeyPlaceholder: 'sk-...',
  modelId: '模型 ID',
  modelIdOptional: '选填',
  modelIdRecommended: '建议填写',
  modelIdPlaceholder: 'gpt-4o, deepseek-chat, claude-opus-4.7',
  saveLocally: '保存到本地',
  runDiagnosis: '开始诊断',
  runningDiagnosis: '诊断进行中…',
  loading: '加载中…',

  // Parse feedback
  parsedOk: '已在本地解析连接信息。',
  parseFailed: '无法解析，请手动填写。',
  urlHintMissingV1: '看起来缺少 /v1，已建议使用 {url}，可手动修改。',

  // Example provider
  needExample: '需要示例？',
  needExampleDesc: '使用示例服务商作为对照。所有诊断逻辑对所有服务商一致。',
  useExample: '使用示例',
  exampleProviderBy: '示例服务商由 Link-AI 提供。',

  // Quick Guide
  quickGuide: '快速指南',
  guideStep1: '粘贴 New API 连接信息，或手动填写 Base URL 和 API Key。',
  guideStep2: '填写模型 ID，或到模型页面选择模型。',
  guideStep3: '点击开始诊断。',
  guideStep4: '复制报告发给站长或客服排查问题。',

  // Diagnosis result labels
  passed: '通过',
  ready: '就绪',
  needsAttention: '需要处理',
  failed: '失败',
  skipped: '已跳过',

  // Diagnosis steps
  baseUrlFormat: '地址格式',
  apiKeyValid: '密钥',
  modelsEndpoint: '模型列表接口',
  modelSelected: '模型选择',
  chatCompletion: '对话接口测试',
  usageReported: '用量返回',
  usageAudit: '用量核对',

  // Report card
  diagnosisResult: '诊断结果',
  status: '状态',
  checks: '已通过',
  checksPassed: '已通过 {passed} / {total} 项',
  provider: '服务商',
  baseUrl_: '接口地址',
  model: '模型',
  modelNotSelected: '未选择',
  mainIssue: '主要问题',
  noMajorIssue: '未发现主要问题',
  httpStatus: 'HTTP 状态码',
  providerMessage: '服务商返回',
  suggestion: '建议',
  na: '暂无',
  usage: '用量',
  usageReportFormat: '用量：{total} total（{prompt} prompt，{completion} completion）',
  usageNotReported: '未返回用量',
  usageSkipped: '未测试用量',
  latency: '延迟',
  tokensPerSec: 'tokens/s',
  reportFooter: 'Generated by AI API Doctor',
  reportUrl: 'aiapidoctor.com',

  // Copy buttons
  copyMarkdown: '复制 Markdown',
  copyIssue: '复制 Issue',
  copyResultText: '复制结果文本',
  copied: '已复制！',
  copyFailed: '复制失败',

  // Usage audit
  usageAvailable: '正常',
  usageNotReportedBadge: '未返回',
  usageAnomaly: '数据异常',
  usageSkippedBadge: '已跳过',
  usagePromptTokens: 'prompt tokens',
  usageCompletionTokens: 'completion tokens',
  usageTotalTokens: 'total tokens',
  collapse: '收起',
  expand: '展开',

  // Models page
  models: '模型',
  searchModels: '搜索模型…',
  modelsLoaded: '个模型',
  enterManually: '手动输入',
  manualModelHint: '部分中转服务不支持 /v1/models 接口，可手动输入模型 ID。',
  setActive: '设为当前',
  test: '测试',
  cancel: '取消',
  refresh: '刷新',
  noModelsLoaded: '未加载到模型。',
  enterModelManuallyOrRetry: '手动输入模型 ID 或重试。',
  testing: '测试中…',
  testConnectivity: '测试连通性',
  connectivityOk: '连接正常',
  active: '当前',
  modelsNoConfigTitle: '未配置',
  modelsNoConfigDesc: '请先在首页填写 Base URL 和 API Key。',

  // Export page
  export: '导出',
  configuration: '配置预览',
  download: '下载',
  exportNote: '导出的内容包含 API 密钥，请妥善保管。',
  noConfigExport: '请先在首页配置 API。',
  exportCline: 'Cline',
  exportContinue: 'Continue',
  exportOpenAI: 'OpenAI SDK',
  exportCurl: 'cURL',
  exportEnv: '.env',

  // Help page
  help: '帮助',
  quickGuideTitle: '快速指南',
  helpFaq: '常见问题',
  helpFaqDesc: 'FAQ',
  modelGroupError: '403 分组错误',
  modelGroupErrorDesc: '403 Model Group Error',
  tokenUsageAudit: 'Token 消耗核对',
  tokenUsageAuditDesc: 'Token Usage Audit',
  aboutTitle: '关于',
  aboutDescription: 'AI API Doctor 由 @norike0718 发起并公开构建。',
  aboutDescription2: 'Link-AI 是项目赞助方和示例服务商之一。AI API Doctor 支持任何 OpenAI-compatible API，诊断逻辑不会因服务商不同而改变。',
};

// ─── Dictionary map ────────────────────────────────────────

const translations: Record<'zh-CN' | 'en-US', Translations> = {
  'zh-CN': zh,
  'en-US': en,
};

// ─── Translation function ────────────────────────────────

export function t(lang: 'zh-CN' | 'en-US', key: keyof Translations): string {
  return translations[lang]?.[key] ?? translations['en-US']?.[key] ?? String(key);
}
